// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-properties.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_properties_default = defineTool({
  name: "list_properties",
  title: "Listar im\xF3veis",
  description: "Lista im\xF3veis publicados no site (t\xEDtulo, bairro, quartos, pre\xE7o, slug).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Quantos im\xF3veis retornar"),
    neighborhood: z.string().optional().describe("Filtrar por bairro (cont\xE9m)"),
    min_bedrooms: z.number().int().optional().describe("M\xEDnimo de quartos")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, neighborhood, min_bedrooms }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("properties").select("id,title,slug,neighborhood,bedrooms,bathrooms,parking,area_useful,price_sale,is_published").eq("is_published", true).order("created_at", { ascending: false }).limit(limit);
    if (neighborhood) query = query.ilike("neighborhood", `%${neighborhood}%`);
    if (typeof min_bedrooms === "number") query = query.gte("bedrooms", min_bedrooms);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { properties: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-crm-contacts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_crm_contacts_default = defineTool2({
  name: "list_crm_contacts",
  title: "Listar contatos do CRM",
  description: "Lista contatos do CRM (requer permiss\xE3o de admin). Filtra por busca, origem ou status.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(25),
    search: z2.string().optional().describe("Busca por nome, telefone ou e-mail"),
    status: z2.string().optional().describe("Filtrar por status"),
    source: z2.string().optional().describe("Filtrar por origem (source_last)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search, status, source }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let query = supabaseForUser2(ctx).from("crm_contacts").select("id,name,raw_phone,raw_email,status,source_first,source_last,ai_score,last_interaction_at,created_at").order("last_interaction_at", { ascending: false }).limit(limit);
    if (search) {
      const s = search.replace(/[%,()]/g, "");
      query = query.or(`name.ilike.%${s}%,raw_phone.ilike.%${s}%,raw_email.ilike.%${s}%`);
    }
    if (status) query = query.eq("status", status);
    if (source) query = query.eq("source_last", source);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { contacts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-crm-contact.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_crm_contact_default = defineTool3({
  name: "get_crm_contact",
  title: "Detalhes de contato CRM",
  description: "Retorna o contato e sua linha do tempo de eventos (formul\xE1rios, notas, intera\xE7\xF5es).",
  inputSchema: {
    contact_id: z3.string().uuid().describe("ID do contato no CRM"),
    events_limit: z3.number().int().min(1).max(100).default(30)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ contact_id, events_limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const [{ data: contact, error: cErr }, { data: events, error: eErr }] = await Promise.all([
      supabase.from("crm_contacts").select("*").eq("id", contact_id).maybeSingle(),
      supabase.from("crm_events").select("id,type,source,title,payload,created_at").eq("contact_id", contact_id).order("created_at", { ascending: false }).limit(events_limit)
    ]);
    if (cErr) return { content: [{ type: "text", text: cErr.message }], isError: true };
    if (eErr) return { content: [{ type: "text", text: eErr.message }], isError: true };
    if (!contact) return { content: [{ type: "text", text: "Contato n\xE3o encontrado" }], isError: true };
    const result = { contact, events: events ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/add-crm-note.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_crm_note_default = defineTool4({
  name: "add_crm_note",
  title: "Adicionar nota ao CRM",
  description: "Registra uma nota interna na linha do tempo de um contato do CRM.",
  inputSchema: {
    contact_id: z4.string().uuid(),
    note: z4.string().min(1).max(2e3).describe("Conte\xFAdo da nota")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ contact_id, note }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("crm_events").insert({
      contact_id,
      type: "note",
      source: "mcp",
      title: "Nota (via assistente)",
      payload: { note }
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: "Nota registrada." }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "atmsbgapyenaikbpjtuz";
var mcp_default = defineMcp({
  name: "perola-patriani-mcp",
  title: "P\xE9rola Patriani \xB7 MCP",
  version: "0.1.0",
  instructions: "Ferramentas do site da P\xE9rola Patriani. Use list_properties para consultar im\xF3veis publicados, e as ferramentas de CRM (list_crm_contacts, get_crm_contact, add_crm_note) para gerenciar leads \u2014 exigem conta com permiss\xE3o de admin.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_properties_default, list_crm_contacts_default, get_crm_contact_default, add_crm_note_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
